version: '3.3'

services:
  db:
    image: mysql:8
    container_name: database
    environment:
      MYSQL_USER: 'db'
      MYSQL_PASSWORD: 'db'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    volumes:
      - ~/apps/mysql:/var/lib/mysql