version: '3.3'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_USER: 'weather'
      MYSQL_PASSWORD: 'weather'
      MYSQL_ROOT_PASSWORD: ''
    ports:
      - '3306:3306'
    volumes:
      - ~/apps/mysql:/var/lib/mysql